CREATE PROCEDURE [Ledger].[sp_AddIncomeWithTransaction]
    -- Shared Parameters
    @UserId INT,
    @WalletId INT,
    @Amount DECIMAL(18,2),
    @IncomeDate DATETIME,
    @Title NVARCHAR(255),
    @TagId INT = NULL,

    -- Transaction Only PARAMETERS
    @Description NVARCHAR(MAX) = NULL,
    @AmountInSp DECIMAL(18,2) = 0,
    @TransactionType INT = 0, 
    @GoalId INT = NULL,
    @DebtId INT = NULL,
    @FixedIncomeId INT = NULL,
    @FixedExpenseId INT = NULL,

    -- OUTPUT PARAMETERS
    @NewIncomeID INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        -- ==========================================
        -- PRE-FLIGHT SECURITY CHECKS 
        -- ==========================================
        IF NOT EXISTS (SELECT 1 FROM [Banking].Wallets WHERE WalletID = @WalletId)
        BEGIN
            ;THROW 50001, 'Wallet not found.', 1;
        END

        IF NOT EXISTS (SELECT 1 FROM [Banking].Wallets WHERE WalletID = @WalletId AND UserID = @UserId)
        BEGIN
            ;THROW 50003, 'Access denied. You do not own this wallet.', 1;
        END

        BEGIN TRAN; 

        -- 2. INSERT INTO TRANSACTIONS FIRST
        -- This generates the Identity ID that the Income will inherit
        INSERT INTO [Ledger].[Transactions] (
            UserID, WalletID, TagID, Title, Amount, 
            AmountInSp, TransactionDate, TransactionType, 
            [Description], GoalID, DebtID, FixedIncomeID, FixedExpenseID
        )
        VALUES (
            @UserId, @WalletId, @TagId, @Title, @Amount, 
            @AmountInSp, @IncomeDate, @TransactionType, 
            @Description, @GoalId, @DebtId, @FixedIncomeId, @FixedExpenseId
        );
        
        -- Capture the ID generated by the Transactions table
        SET @NewIncomeID = SCOPE_IDENTITY();

        -- 3. INSERT INTO INCOMES SECOND
        -- Note: IncomeID is NOT an identity; we force it to match @NewIncomeID
        INSERT INTO [Ledger].[Incomes] (
            IncomeID, UserID, WalletID, TagID, 
            Title, Amount, [Date]
        )
        VALUES (
            @NewIncomeID, @UserId, @WalletId, @TagId, 
            @Title, @Amount, @IncomeDate
        );

        -- 4. UPDATE WALLET BALANCE (ADD FOR INCOME)
        UPDATE [Banking].[Wallets]
        SET Balance = Balance + @Amount
        WHERE WalletID = @WalletId AND UserID = @UserId;

        COMMIT TRAN; 

        -- Return the ID to the application
        SELECT @NewIncomeID AS NewIncomeID;

    END TRY
    BEGIN CATCH
        -- Ensure the entire operation is rolled back if ANY step fails
        IF @@TRANCOUNT > 0 ROLLBACK TRAN; 
        THROW; 
    END CATCH
END