using SpendWise.Application.DTOs.SharedDebts;
using SpendWise.Application.Interfaces.ExchangeRate;
using SpendWise.Application.Interfaces.SharedDebts;
using SpendWise.Domain.Constants;
using SpendWise.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SpendWise.Application.Services
{
    public class SharedDebtService : ISharedDebtService
    {
        private readonly ISharedDebtRepository _debtRepo;
        private readonly IExchangeRateService _exchangeRateService;

        public SharedDebtService(ISharedDebtRepository debtRepo, IExchangeRateService exchangeRateService)
        {
            _debtRepo = debtRepo;
            _exchangeRateService = exchangeRateService;
        }

        public async Task<IEnumerable<SharedDebtResponse>> GetDebtsOwedToUserAsync(int userId)
        {
            var debts = await _debtRepo.GetDebtsOwedToUserAsync(userId);
            return debts.Select(item => new SharedDebtResponse(item));
        }

        public async Task<IEnumerable<SharedDebtResponse>> GetTheDebtsIHaveToPayAsync(int userId)
        {
            var debts = await _debtRepo.GetTheDebtsIHaveToPayAsync(userId);
            return debts.Select(item => new SharedDebtResponse(item));
        }

        public async Task<SharedDebtResponse?> GetDebtByIdAsync(int debtId)
        {
            var debt = await _debtRepo.GetDebtByIdAsync(debtId);
            return debt != null ? new SharedDebtResponse(debt) : null;
        }

        public async Task<SharedDebtResponse?> GetDebtByTitleAsync(string title)
        {
            var debt = await _debtRepo.GetDebtByTitleAsync(title);
            return debt != null ? new SharedDebtResponse(debt) : null;
        }

        public async Task<int> AddDebtAsync(SharedDebtDTO debtDto)
        {
            // Create entity from DTO (Setting ID to -1 as it's generated by DB)
            var debt = new SharedDebt(
                -1,
                debtDto.CreditorID,
                debtDto.DebtorID,
                debtDto.Amount,
                debtDto.Title,
                debtDto.Status,
                debtDto.CreatedAt,
                debtDto.DueDate,
                debtDto.CreditorWalletID,
                debtDto.DebtorWalletID,
                0 // Initial PaidAmount is 0
            );

            return await _debtRepo.AddDebtAsync(debt);
        }

        public async Task<bool> UpdateDebtAsync(int debtId, SharedDebtDTO debtDto)
        {
            // Create entity from DTO using the existing debtId
            var debt = new SharedDebt(
                debtId,
                debtDto.CreditorID,
                debtDto.DebtorID,
                debtDto.Amount,
                debtDto.Title,
                debtDto.Status,
                debtDto.CreatedAt,
                debtDto.DueDate,
                debtDto.CreditorWalletID,
                debtDto.DebtorWalletID,
                debtDto.PaidAmount
            );

            return await _debtRepo.UpdateDebtAsync(debt);
        }

        public async Task<bool> DeleteDebtByIdAsync(int debtId)
        {
            return await _debtRepo.DeleteDebtByIdAsync(debtId);
        }

        public async Task<bool> DeletDebtByTitleAsync(string title)
        {
            return await _debtRepo.DeleteDebtByTitleAsync(title);
        }

        public async Task<IEnumerable<SharedDebtResponse>> GetSharedDebtsForUserAsync(int userId)
        {
            var debts = await _debtRepo.GetSharedDebtsForUserAsync(userId);
            return debts.Select(item => new SharedDebtResponse(item));
        }

        public async Task<bool> ReturnDebtAmountAsync(int debtId, ReturnDebtDTO returnDebtDTO)
        {
            var debt = new SharedDebt(
                debtId,
                returnDebtDTO.DebtDTO.CreditorID,
                returnDebtDTO.DebtDTO.DebtorID,
                returnDebtDTO.DebtDTO.Amount,
                returnDebtDTO.DebtDTO.Title,
                returnDebtDTO.DebtDTO.Status,
                returnDebtDTO.DebtDTO.CreatedAt,
                returnDebtDTO.DebtDTO.DueDate,
                returnDebtDTO.DebtDTO.CreditorWalletID,
                returnDebtDTO.DebtDTO.DebtorWalletID,
                returnDebtDTO.DebtDTO.PaidAmount
            );

            decimal amountInSp = await _exchangeRateService.NormalizeToSyrianPound(SupportedCurrencies.GetById(returnDebtDTO.DebtDTO.DebtorWalletID).Code, "Damascus", "black_market", Convert.ToDecimal(returnDebtDTO.Amount));

            return await _debtRepo.ReturnDebtAmountAsync(debt, returnDebtDTO.Amount, returnDebtDTO.Title, returnDebtDTO.Description, amountInSp);
        }

        public async Task<bool> DebtExistsAsyns(int debtId)
        {
            return await _debtRepo.DebtExistsAsync(debtId);
        }

        public async Task<bool> AcceptSharedDebtAsync(int debtId, ReturnDebtDTO returnDebtDTO)
        {
            var debt = new SharedDebt(
                debtId,
                returnDebtDTO.DebtDTO.CreditorID,
                returnDebtDTO.DebtDTO.DebtorID,
                returnDebtDTO.DebtDTO.Amount,
                returnDebtDTO.DebtDTO.Title,
                returnDebtDTO.DebtDTO.Status,
                returnDebtDTO.DebtDTO.CreatedAt,
                returnDebtDTO.DebtDTO.DueDate,
                returnDebtDTO.DebtDTO.CreditorWalletID,
                returnDebtDTO.DebtDTO.DebtorWalletID,
                returnDebtDTO.DebtDTO.PaidAmount
            );
            decimal amountInSp = await _exchangeRateService.NormalizeToSyrianPound(SupportedCurrencies.GetById(returnDebtDTO.DebtDTO.DebtorWalletID).Code, "Damascus", "black_market", Convert.ToDecimal(returnDebtDTO.Amount));

            return await _debtRepo.AcceptDebtAsync(debt, returnDebtDTO.Amount, returnDebtDTO.Title, returnDebtDTO.Description, amountInSp);
        }

        public async Task<bool> RefuseDebtAsync(int debtId)
        {
            return await _debtRepo.RefuseDebtAsync(debtId);
        }
    }
}