INSERT INTO Config.Currencies (CurrencyName, ActualValue)
VALUES 
    ('Afghan Afghani', 1),
    ('Albanian Lek', 1),
    ('Algerian Dinar', 1),
    ('Angolan Kwanza', 1),
    ('Argentine Peso', 1),
    ('Armenian Dram', 1),
    ('Aruban Florin', 1),
    ('Australian Dollar', 1),
    ('Azerbaijani Manat', 1),
    ('Bahamian Dollar', 1),
    ('Bahraini Dinar', 1),
    ('Bangladeshi Taka', 1),
    ('Barbadian Dollar', 1),
    ('Belarusian Ruble', 1),
    ('Belize Dollar', 1),
    ('Bermudian Dollar', 1),
    ('Bhutanese Ngultrum', 1),
    ('Bolivian Boliviano', 1),
    ('Bosnia and Herzegovina Convertible Mark', 1),
    ('Botswana Pula', 1),
    ('Brazilian Real', 1),
    ('Brunei Dollar', 1),
    ('Bulgarian Lev', 1),
    ('Burundian Franc', 1),
    ('Cambodian Riel', 1),
    ('Canadian Dollar', 1),
    ('Cape Verdean Escudo', 1),
    ('Cayman Islands Dollar', 1),
    ('Central African CFA Franc', 1),
    ('Chilean Peso', 1),
    ('Chinese Yuan Renminbi', 1),
    ('Colombian Peso', 1),
    ('Comorian Franc', 1),
    ('Congolese Franc', 1),
    ('Costa Rican Colon', 1),
    ('Croatian Kuna', 1),
    ('Cuban Peso', 1),
    ('Czech Koruna', 1),
    ('Danish Krone', 1),
    ('Djiboutian Franc', 1),
    ('Dominican Peso', 1),
    ('East Caribbean Dollar', 1),
    ('Egyptian Pound', 1),
    ('Eritrean Nakfa', 1),
    ('Ethiopian Birr', 1),
    ('Euro', 1),
    ('Falkland Islands Pound', 1),
    ('Fijian Dollar', 1),
    ('Gambian Dalasi', 1),
    ('Georgian Lari', 1),
    ('Ghanaian Cedi', 1),
    ('Gibraltar Pound', 1),
    ('Guatemalan Quetzal', 1),
    ('Guinean Franc', 1),
    ('Guyanese Dollar', 1),
    ('Haitian Gourde', 1),
    ('Honduran Lempira', 1),
    ('Hong Kong Dollar', 1),
    ('Hungarian Forint', 1),
    ('Icelandic Krona', 1),
    ('Indian Rupee', 1),
    ('Indonesian Rupiah', 1),
    ('Iranian Rial', 1),
    ('Iraqi Dinar', 1),
    ('Jamaican Dollar', 1),
    ('Japanese Yen', 1),
    ('Jordanian Dinar', 1),
    ('Kazakhstani Tenge', 1),
    ('Kenyan Shilling', 1),
    ('Kuwaiti Dinar', 1),
    ('Kyrgyzstani Som', 1),
    ('Lao Kip', 1),
    ('Lebanese Pound', 1),
    ('Lesotho Loti', 1),
    ('Liberian Dollar', 1),
    ('Libyan Dinar', 1),
    ('Macanese Pataca', 1),
    ('Macedonian Denar', 1),
    ('Malagasy Ariary', 1),
    ('Malawian Kwacha', 1),
    ('Malaysian Ringgit', 1),
    ('Maldivian Rufiyaa', 1),
    ('Mauritanian Ouguiya', 1),
    ('Mauritian Rupee', 1),
    ('Mexican Peso', 1),
    ('Moldovan Leu', 1),
    ('Mongolian Tugrik', 1),
    ('Moroccan Dirham', 1),
    ('Mozambican Metical', 1),
    ('Myanmar Kyat', 1),
    ('Namibian Dollar', 1),
    ('Nepalese Rupee', 1),
    ('Netherlands Antillean Guilder', 1),
    ('New Taiwan Dollar', 1),
    ('New Zealand Dollar', 1),
    ('Nicaraguan Cordoba', 1),
    ('Nigerian Naira', 1),
    ('North Korean Won', 1),
    ('Norwegian Krone', 1),
    ('Omani Rial', 1),
    ('Pakistani Rupee', 1),
    ('Panamanian Balboa', 1),
    ('Papua New Guinean Kina', 1),
    ('Paraguayan Guarani', 1),
    ('Peruvian Sol', 1),
    ('Philippine Peso', 1),
    ('Polish Zloty', 1),
    ('Qatari Riyal', 1),
    ('Romanian Leu', 1),
    ('Russian Ruble', 1),
    ('Rwandan Franc', 1),
    ('Saint Helena Pound', 1),
    ('Samoan Tala', 1),
    ('Sao Tome and Principe Dobra', 1),
    ('Saudi Riyal', 1),
    ('Serbian Dinar', 1),
    ('Seychellois Rupee', 1),
    ('Sierra Leonean Leone', 1),
    ('Singapore Dollar', 1),
    ('Solomon Islands Dollar', 1),
    ('Somali Shilling', 1),
    ('South African Rand', 1),
    ('South Korean Won', 1),
    ('South Sudanese Pound', 1),
    ('Sri Lankan Rupee', 1),
    ('Sudanese Pound', 1),
    ('Surinamese Dollar', 1),
    ('Swazi Lilangeni', 1),
    ('Swedish Krona', 1),
    ('Swiss Franc', 1),
    ('Syrian Pound', 1),
    ('Tajikistani Somoni', 1),
    ('Tanzanian Shilling', 1),
    ('Thai Baht', 1),
    ('Tongan Pa''anga', 1), -- Escaped single quote
    ('Trinidad and Tobago Dollar', 1),
    ('Tunisian Dinar', 1),
    ('Turkish Lira', 1),
    ('Turkmenistani Manat', 1),
    ('Ugandan Shilling', 1),
    ('Ukrainian Hryvnia', 1),
    ('United Arab Emirates Dirham', 1),
    ('United Kingdom Pound Sterling', 1),
    ('United States Dollar', 1),
    ('Uruguayan Peso', 1),
    ('Uzbekistani Som', 1),
    ('Vanuatu Vatu', 1),
    ('Venezuelan Bolívar Soberano', 1),
    ('Vietnamese Dong', 1),
    ('West African CFA Franc', 1),
    ('Yemeni Rial', 1),
    ('Zambian Kwacha', 1),
    ('Zimbabwean Dollar', 1);
