using SpendWise.Domain.Entities;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace SpendWise.Domain.Constants
{
    public static class SupportedCurrencies
    {
        public const int SyrianPoundId = 131; 

        public static readonly IReadOnlyDictionary<int, Currency> Map = new Dictionary<int, Currency>
        {
            { 1, new Currency(1, "AFN", "Afghan Afghani") },
            { 2, new Currency(2, "ALL", "Albanian Lek") },
            { 3, new Currency(3, "DZD", "Algerian Dinar") },
            { 4, new Currency(4, "AOA", "Angolan Kwanza") },
            { 5, new Currency(5, "ARS", "Argentine Peso") },
            { 6, new Currency(6, "AMD", "Armenian Dram") },
            { 7, new Currency(7, "AWG", "Aruban Florin") },
            { 8, new Currency(8, "AUD", "Australian Dollar") },
            { 9, new Currency(9, "AZN", "Azerbaijani Manat") },
            { 10, new Currency(10, "BSD", "Bahamian Dollar") },
            { 11, new Currency(11, "BHD", "Bahraini Dinar") },
            { 12, new Currency(12, "BDT", "Bangladeshi Taka") },
            { 13, new Currency(13, "BBD", "Barbadian Dollar") },
            { 14, new Currency(14, "BYN", "Belarusian Ruble") },
            { 15, new Currency(15, "BZD", "Belize Dollar") },
            { 16, new Currency(16, "BMD", "Bermudian Dollar") },
            { 17, new Currency(17, "BTN", "Bhutanese Ngultrum") },
            { 18, new Currency(18, "BOB", "Bolivian Boliviano") },
            { 19, new Currency(19, "BAM", "Bosnia and Herzegovina Convertible Mark") },
            { 20, new Currency(20, "BWP", "Botswana Pula") },
            { 21, new Currency(21, "BRL", "Brazilian Real") },
            { 22, new Currency(22, "BND", "Brunei Dollar") },
            { 23, new Currency(23, "BGN", "Bulgarian Lev") },
            { 24, new Currency(24, "BIF", "Burundian Franc") },
            { 25, new Currency(25, "KHR", "Cambodian Riel") },
            { 26, new Currency(26, "CAD", "Canadian Dollar") },
            { 27, new Currency(27, "CVE", "Cape Verdean Escudo") },
            { 28, new Currency(28, "KYD", "Cayman Islands Dollar") },
            { 29, new Currency(29, "XAF", "Central African CFA Franc") },
            { 30, new Currency(30, "CLP", "Chilean Peso") },
            { 31, new Currency(31, "CNY", "Chinese Yuan Renminbi") },
            { 32, new Currency(32, "COP", "Colombian Peso") },
            { 33, new Currency(33, "KMF", "Comorian Franc") },
            { 34, new Currency(34, "CDF", "Congolese Franc") },
            { 35, new Currency(35, "CRC", "Costa Rican Colon") },
            { 36, new Currency(36, "HRK", "Croatian Kuna") },
            { 37, new Currency(37, "CUP", "Cuban Peso") },
            { 38, new Currency(38, "CZK", "Czech Koruna") },
            { 39, new Currency(39, "DKK", "Danish Krone") },
            { 40, new Currency(40, "DJF", "Djiboutian Franc") },
            { 41, new Currency(41, "DOP", "Dominican Peso") },
            { 42, new Currency(42, "XCD", "East Caribbean Dollar") },
            { 43, new Currency(43, "EGP", "Egyptian Pound") },
            { 44, new Currency(44, "ERN", "Eritrean Nakfa") },
            { 45, new Currency(45, "ETB", "Ethiopian Birr") },
            { 46, new Currency(46, "EUR", "Euro") },
            { 47, new Currency(47, "FKP", "Falkland Islands Pound") },
            { 48, new Currency(48, "FJD", "Fijian Dollar") },
            { 49, new Currency(49, "GMD", "Gambian Dalasi") },
            { 50, new Currency(50, "GEL", "Georgian Lari") },
            { 51, new Currency(51, "GHS", "Ghanaian Cedi") },
            { 52, new Currency(52, "GIP", "Gibraltar Pound") },
            { 53, new Currency(53, "GTQ", "Guatemalan Quetzal") },
            { 54, new Currency(54, "GNF", "Guinean Franc") },
            { 55, new Currency(55, "GYD", "Guyanese Dollar") },
            { 56, new Currency(56, "HTG", "Haitian Gourde") },
            { 57, new Currency(57, "HNL", "Honduran Lempira") },
            { 58, new Currency(58, "HKD", "Hong Kong Dollar") },
            { 59, new Currency(59, "HUF", "Hungarian Forint") },
            { 60, new Currency(60, "ISK", "Icelandic Krona") },
            { 61, new Currency(61, "INR", "Indian Rupee") },
            { 62, new Currency(62, "IDR", "Indonesian Rupiah") },
            { 63, new Currency(63, "IRR", "Iranian Rial") },
            { 64, new Currency(64, "IQD", "Iraqi Dinar") },
            { 65, new Currency(65, "JMD", "Jamaican Dollar") },
            { 66, new Currency(66, "JPY", "Japanese Yen") },
            { 67, new Currency(67, "JOD", "Jordanian Dinar") },
            { 68, new Currency(68, "KZT", "Kazakhstani Tenge") },
            { 69, new Currency(69, "KES", "Kenyan Shilling") },
            { 70, new Currency(70, "KWD", "Kuwaiti Dinar") },
            { 71, new Currency(71, "KGS", "Kyrgyzstani Som") },
            { 72, new Currency(72, "LAK", "Lao Kip") },
            { 73, new Currency(73, "LBP", "Lebanese Pound") },
            { 74, new Currency(74, "LSL", "Lesotho Loti") },
            { 75, new Currency(75, "LRD", "Liberian Dollar") },
            { 76, new Currency(76, "LYD", "Libyan Dinar") },
            { 77, new Currency(77, "MOP", "Macanese Pataca") },
            { 78, new Currency(78, "MKD", "Macedonian Denar") },
            { 79, new Currency(79, "MGA", "Malagasy Ariary") },
            { 80, new Currency(80, "MWK", "Malawian Kwacha") },
            { 81, new Currency(81, "MYR", "Malaysian Ringgit") },
            { 82, new Currency(82, "MVR", "Maldivian Rufiyaa") },
            { 83, new Currency(83, "MRU", "Mauritanian Ouguiya") },
            { 84, new Currency(84, "MUR", "Mauritian Rupee") },
            { 85, new Currency(85, "MXN", "Mexican Peso") },
            { 86, new Currency(86, "MDL", "Moldovan Leu") },
            { 87, new Currency(87, "MNT", "Mongolian Tugrik") },
            { 88, new Currency(88, "MAD", "Moroccan Dirham") },
            { 89, new Currency(89, "MZN", "Mozambican Metical") },
            { 90, new Currency(90, "MMK", "Myanmar Kyat") },
            { 91, new Currency(91, "NAD", "Namibian Dollar") },
            { 92, new Currency(92, "NPR", "Nepalese Rupee") },
            { 93, new Currency(93, "ANG", "Netherlands Antillean Guilder") },
            { 94, new Currency(94, "TWD", "New Taiwan Dollar") },
            { 95, new Currency(95, "NZD", "New Zealand Dollar") },
            { 96, new Currency(96, "NIO", "Nicaraguan Cordoba") },
            { 97, new Currency(97, "NGN", "Nigerian Naira") },
            { 98, new Currency(98, "KPW", "North Korean Won") },
            { 99, new Currency(99, "NOK", "Norwegian Krone") },
            { 100, new Currency(100, "OMR", "Omani Rial") },
            { 101, new Currency(101, "PKR", "Pakistani Rupee") },
            { 102, new Currency(102, "PAB", "Panamanian Balboa") },
            { 103, new Currency(103, "PGK", "Papua New Guinean Kina") },
            { 104, new Currency(104, "PYG", "Paraguayan Guarani") },
            { 105, new Currency(105, "PEN", "Peruvian Sol") },
            { 106, new Currency(106, "PHP", "Philippine Peso") },
            { 107, new Currency(107, "PLN", "Polish Zloty") },
            { 108, new Currency(108, "QAR", "Qatari Riyal") },
            { 109, new Currency(109, "RON", "Romanian Leu") },
            { 110, new Currency(110, "RUB", "Russian Ruble") },
            { 111, new Currency(111, "RWF", "Rwandan Franc") },
            { 112, new Currency(112, "SHP", "Saint Helena Pound") },
            { 113, new Currency(113, "WST", "Samoan Tala") },
            { 114, new Currency(114, "STN", "Sao Tome and Principe Dobra") },
            { 115, new Currency(115, "SAR", "Saudi Riyal") },
            { 116, new Currency(116, "RSD", "Serbian Dinar") },
            { 117, new Currency(117, "SCR", "Seychellois Rupee") },
            { 118, new Currency(118, "SLL", "Sierra Leonean Leone") },
            { 119, new Currency(119, "SGD", "Singapore Dollar") },
            { 120, new Currency(120, "SBD", "Solomon Islands Dollar") },
            { 121, new Currency(121, "SOS", "Somali Shilling") },
            { 122, new Currency(122, "ZAR", "South African Rand") },
            { 123, new Currency(123, "KRW", "South Korean Won") },
            { 124, new Currency(124, "SSP", "South Sudanese Pound") },
            { 125, new Currency(125, "LKR", "Sri Lankan Rupee") },
            { 126, new Currency(126, "SDG", "Sudanese Pound") },
            { 127, new Currency(127, "SRD", "Surinamese Dollar") },
            { 128, new Currency(128, "SZL", "Swazi Lilangeni") },
            { 129, new Currency(129, "SEK", "Swedish Krona") },
            { 130, new Currency(130, "CHF", "Swiss Franc") },
            { 131, new Currency(131, "SYP", "Syrian Pound") },
            { 132, new Currency(132, "TJS", "Tajikistani Somoni") },
            { 133, new Currency(133, "TZS", "Tanzanian Shilling") },
            { 134, new Currency(134, "THB", "Thai Baht") },
            { 135, new Currency(135, "TOP", "Tongan Pa'anga") },
            { 136, new Currency(136, "TTD", "Trinidad and Tobago Dollar") },
            { 137, new Currency(137, "TND", "Tunisian Dinar") },
            { 138, new Currency(138, "TRY", "Turkish Lira") },
            { 139, new Currency(139, "TMT", "Turkmenistani Manat") },
            { 140, new Currency(140, "UGX", "Ugandan Shilling") },
            { 141, new Currency(141, "UAH", "Ukrainian Hryvnia") },
            { 142, new Currency(142, "AED", "United Arab Emirates Dirham") },
            { 143, new Currency(143, "GBP", "United Kingdom Pound Sterling") },
            { 144, new Currency(144, "USD", "United States Dollar") },
            { 145, new Currency(145, "UYU", "Uruguayan Peso") },
            { 146, new Currency(146, "UZS", "Uzbekistani Som") },
            { 147, new Currency(147, "VUV", "Vanuatu Vatu") },
            { 148, new Currency(148, "VES", "Venezuelan Bolívar Soberano") },
            { 149, new Currency(149, "VND", "Vietnamese Dong") },
            { 150, new Currency(150, "XOF", "West African CFA Franc") },
            { 151, new Currency(151, "YER", "Yemeni Rial") },
            { 152, new Currency(152, "ZMW", "Zambian Kwacha") },
            { 153, new Currency(153, "ZWL", "Zimbabwean Dollar") }
        }.AsReadOnly();

        /// <summary>
        /// Instantly retrieves a currency by its ID, or returns null if not found.
        /// </summary>
        public static Currency? GetById(int id)
        {
            return Map.TryGetValue(id, out var currency) ? currency : null;
        }

        /// <summary>
        /// Returns all currencies, useful for populating frontend dropdowns.
        /// </summary>
        public static IEnumerable<Currency> GetAll() => Map.Values;
    }
}