<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0d3dc77e-d53c-4472-a590-800a972d1267</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
	<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpendWise.Application\SpendWise.Application.csproj" />
    <ProjectReference Include="..\SpendWise.Infrastructure\SpendWise.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
	<None Update="appsettings.Development.json">
		<DependentUpon>appsettings.json</DependentUpon>
	</None>
  </ItemGroup>

  <ItemGroup>
	<Content Include="tessdata\**\*">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</Content>
  </ItemGroup>

</Project>
