import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:spendwise/core/utils/colors.dart';
import 'package:spendwise/features/tags/data/models/tag_model.dart';
import 'package:spendwise/features/tags/presentation/manager/tag_controller.dart';
import 'package:spendwise/features/tags/presentation/pages/tags_view.dart';
import 'package:spendwise/features/widget_feature/helper_widget/custom_button.dart';
import 'package:spendwise/features/widget_feature/helper_widget/custom_text_field.dart';
import 'package:spendwise/features/widget_feature/helper_widget/dropdown_button.dart';

class AddtagPage extends StatefulWidget {
  const AddtagPage({super.key});

  @override
  State<AddtagPage> createState() => _AddtagPageState();
}

class _AddtagPageState extends State<AddtagPage> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  TagController tagController = TagController.instance;

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  void _submit() {
    if (!(_formKey.currentState?.validate() ?? false)) return;

    tagController.addtag(
      TagModel(
        id: 1, // // Note: Ideally generated by backend or database
        ownerId: 2,
        label: _nameController.text.trim(),
        categoryId: 1,
      ),
    );

    Get.back();
    Get.snackbar(
      "Success",
      "Tag added successfully",
      snackPosition: SnackPosition.BOTTOM,
      backgroundColor: Colors.green.withOpacity(0.1),
      colorText: Colors.green,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: SpColor.primaryDark2,
      appBar: AppBar(
        backgroundColor: SpColor.primaryDark2,

        title: const Text(
          "Create New Tag",
          style: TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        elevation: 0,
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(
            Icons.arrow_back_ios_new,
            color: SpColor.accentBlue,
            size: 20,
          ),
          onPressed: () => Get.back(),
        ),
        actions: [
          // // Logic: Moved "Show Tags" to AppBar to clean up the main UI space
          IconButton(
            icon: const Icon(Icons.list_alt_rounded, color: SpColor.accentBlue),
            onPressed: () => Get.to(() => TagsView()),
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const SizedBox(height: 20),

                // // UI Decoration: Adding a descriptive header
                const Text(
                  "Tag Details",
                  style: TextStyle(
                    color: Colors.white70,
                    fontSize: 16,
                    letterSpacing: 1.1,
                  ),
                ),
                const SizedBox(height: 25),

                // // Layout: Grouping inputs inside a container for better visual structure
                Container(
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    color: SpColor.surfaceNavy.withOpacity(0.5),
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(color: Colors.white10),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      CustomTextField(
                        label: "Tag Name",
                        hint: "e.g. Shopping, Bills...",
                        prefixIcon: const Icon(
                          Icons.label_important_outline,
                          color: SpColor.accentBlue,
                        ),
                        textEditingController: _nameController,
                      ),
                      const SizedBox(height: 25),
                      const Text(
                        "Category Type",
                        style: TextStyle(
                          color: SpColor.accentBlue,
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      const SizedBox(height: 10),
                      SPDropdownButton(
                        controller: tagController,
                        title: "category",
                        hint: "Select Category",
                        isTextField: false,
                      ),
                    ],
                  ),
                ),

                const SizedBox(height: 40),

                // // Visual Feedback: Information note for the user
                Row(
                  children: const [
                    Icon(Icons.info_outline, color: Colors.white38, size: 16),
                    SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        "Tags help you categorize your expenses more specifically.",
                        style: TextStyle(color: Colors.white38, fontSize: 12),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),

      // // Logic: Placing the main action button at the bottom for better accessibility
      bottomNavigationBar: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: CustomButton(
            onPressed: _submit,
            text: "Save Tag",
            color: SpColor.accentBlue,
            // // Design: Ensure the button stands out with proper height
          ),
        ),
      ),
    );
  }
}
