<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
	<PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260427" />
	<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
	<PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\SpendWise.Application\SpendWise.Application.csproj" />
    <ProjectReference Include="..\SpendWise.Domain\SpendWise.Domain.csproj" />
  </ItemGroup>

</Project>
